export { default as LoginData } from './LoginData.vue'
export { default as CadastroData } from './CadastroData.vue'
export { default as AlertCard } from './AlertCard.vue'
export { default as  MenuLinkStyled } from './MenuLinkStyled.vue'
export { default as  UpdateData } from './UpdateData.vue'
